name: builds
run-name: ${{ github.actor }} is building ShrVN
on: [push]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up GCC
          uses: egor-tensin/setup-gcc@v1
          with:
            version: latest
            platform: x64

        - name: Install Qt
          uses: jurplel/install-qt-action@v3

        - run: qmake -o Makefile Sources/ShrVN/ShrVN.pro

        - run: make