name: builds
run-name: ${{ github.actor }} is building ShrVN
on: 
  push:
    branches:
      - main
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install Qt
          uses: jurplel/install-qt-action@v3

        - run: qmake -makefile -o Makefile "TEMPLATE = app" Sources/ShrVN/ShrVN.pro

        - run: sed 's/CXX           = g++/CXX           = g++ -std=c++20/g' -i Makefile

        - run: make